package com.ccb.b.c;

import android.content.Context;
import com.baidu.mobstat.Config;
import com.ccb.b.b.b;
import com.ccb.b.b.g;
import com.ccb.b.b.i;
import com.ccb.b.b.j;
import com.ccb.b.b.m;

public class a extends g {
    int b = 0;
    int c = 0;
    private String[] d = {"q", Config.DEVICE_WIDTH, "e", "r", "t", "y", "u", "i", Config.OS, "p", Config.APP_VERSION_CODE, "s", "d", "f", "g", "h", "j", Config.APP_KEY, "l", "z", Config.EVENT_HEAT_X, "c", "v", "b", "n", Config.MODEL};
    private String[] e = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};
    /* access modifiers changed from: private */
    public boolean f = false;

    public a(Context context) {
        super(context);
        setOrientation(1);
        this.b = 0;
        this.c = 0;
        i iVar = new i(getContext());
        Context context2 = getContext();
        String str = this.e[this.c];
        String[] strArr = this.e;
        int i = this.c;
        this.c = i + 1;
        iVar.a(b(new j(context2, str, strArr[i], 0, 1.0f)));
        Context context3 = getContext();
        String str2 = this.e[this.c];
        String[] strArr2 = this.e;
        int i2 = this.c;
        this.c = i2 + 1;
        iVar.a(b(new j(context3, str2, strArr2[i2], 0, 1.0f)));
        Context context4 = getContext();
        String str3 = this.e[this.c];
        String[] strArr3 = this.e;
        int i3 = this.c;
        this.c = i3 + 1;
        iVar.a(b(new j(context4, str3, strArr3[i3], 0, 1.0f)));
        Context context5 = getContext();
        String str4 = this.e[this.c];
        String[] strArr4 = this.e;
        int i4 = this.c;
        this.c = i4 + 1;
        iVar.a(b(new j(context5, str4, strArr4[i4], 0, 1.0f)));
        Context context6 = getContext();
        String str5 = this.e[this.c];
        String[] strArr5 = this.e;
        int i5 = this.c;
        this.c = i5 + 1;
        iVar.a(b(new j(context6, str5, strArr5[i5], 0, 1.0f)));
        Context context7 = getContext();
        String str6 = this.e[this.c];
        String[] strArr6 = this.e;
        int i6 = this.c;
        this.c = i6 + 1;
        iVar.a(b(new j(context7, str6, strArr6[i6], 0, 1.0f)));
        Context context8 = getContext();
        String str7 = this.e[this.c];
        String[] strArr7 = this.e;
        int i7 = this.c;
        this.c = i7 + 1;
        iVar.a(b(new j(context8, str7, strArr7[i7], 0, 1.0f)));
        Context context9 = getContext();
        String str8 = this.e[this.c];
        String[] strArr8 = this.e;
        int i8 = this.c;
        this.c = i8 + 1;
        iVar.a(b(new j(context9, str8, strArr8[i8], 0, 1.0f)));
        Context context10 = getContext();
        String str9 = this.e[this.c];
        String[] strArr9 = this.e;
        int i9 = this.c;
        this.c = i9 + 1;
        iVar.a(b(new j(context10, str9, strArr9[i9], 0, 1.0f)));
        Context context11 = getContext();
        String str10 = this.e[this.c];
        String[] strArr10 = this.e;
        int i10 = this.c;
        this.c = i10 + 1;
        iVar.a(b(new j(context11, str10, strArr10[i10], 0, 1.0f)));
        addView(iVar);
        i iVar2 = new i(getContext());
        Context context12 = getContext();
        String str11 = this.d[this.b];
        String[] strArr11 = this.d;
        int i11 = this.b;
        this.b = i11 + 1;
        iVar2.a(a(new j(context12, str11, strArr11[i11], 0, 1.0f)));
        Context context13 = getContext();
        String str12 = this.d[this.b];
        String[] strArr12 = this.d;
        int i12 = this.b;
        this.b = i12 + 1;
        iVar2.a(a(new j(context13, str12, strArr12[i12], 0, 1.0f)));
        Context context14 = getContext();
        String str13 = this.d[this.b];
        String[] strArr13 = this.d;
        int i13 = this.b;
        this.b = i13 + 1;
        iVar2.a(a(new j(context14, str13, strArr13[i13], 0, 1.0f)));
        Context context15 = getContext();
        String str14 = this.d[this.b];
        String[] strArr14 = this.d;
        int i14 = this.b;
        this.b = i14 + 1;
        iVar2.a(a(new j(context15, str14, strArr14[i14], 0, 1.0f)));
        Context context16 = getContext();
        String str15 = this.d[this.b];
        String[] strArr15 = this.d;
        int i15 = this.b;
        this.b = i15 + 1;
        iVar2.a(a(new j(context16, str15, strArr15[i15], 0, 1.0f)));
        Context context17 = getContext();
        String str16 = this.d[this.b];
        String[] strArr16 = this.d;
        int i16 = this.b;
        this.b = i16 + 1;
        iVar2.a(a(new j(context17, str16, strArr16[i16], 0, 1.0f)));
        Context context18 = getContext();
        String str17 = this.d[this.b];
        String[] strArr17 = this.d;
        int i17 = this.b;
        this.b = i17 + 1;
        iVar2.a(a(new j(context18, str17, strArr17[i17], 0, 1.0f)));
        Context context19 = getContext();
        String str18 = this.d[this.b];
        String[] strArr18 = this.d;
        int i18 = this.b;
        this.b = i18 + 1;
        iVar2.a(a(new j(context19, str18, strArr18[i18], 0, 1.0f)));
        Context context20 = getContext();
        String str19 = this.d[this.b];
        String[] strArr19 = this.d;
        int i19 = this.b;
        this.b = i19 + 1;
        iVar2.a(a(new j(context20, str19, strArr19[i19], 0, 1.0f)));
        Context context21 = getContext();
        String str20 = this.d[this.b];
        String[] strArr20 = this.d;
        int i20 = this.b;
        this.b = i20 + 1;
        iVar2.a(a(new j(context21, str20, strArr20[i20], 0, 1.0f)));
        addView(iVar2);
        i iVar3 = new i(getContext());
        com.ccb.b.b.a aVar = new com.ccb.b.b.a(getContext(), "", null, 115, 1.0f, m.a("up_case.png"), m.a("up_case_press.png"));
        iVar3.a((b) aVar);
        Context context22 = getContext();
        String str21 = this.d[this.b];
        String[] strArr21 = this.d;
        int i21 = this.b;
        this.b = i21 + 1;
        iVar3.a(a(new j(context22, str21, strArr21[i21], 0, 1.0f)));
        Context context23 = getContext();
        String str22 = this.d[this.b];
        String[] strArr22 = this.d;
        int i22 = this.b;
        this.b = i22 + 1;
        iVar3.a(a(new j(context23, str22, strArr22[i22], 0, 1.0f)));
        Context context24 = getContext();
        String str23 = this.d[this.b];
        String[] strArr23 = this.d;
        int i23 = this.b;
        this.b = i23 + 1;
        iVar3.a(a(new j(context24, str23, strArr23[i23], 0, 1.0f)));
        Context context25 = getContext();
        String str24 = this.d[this.b];
        String[] strArr24 = this.d;
        int i24 = this.b;
        this.b = i24 + 1;
        iVar3.a(a(new j(context25, str24, strArr24[i24], 0, 1.0f)));
        Context context26 = getContext();
        String str25 = this.d[this.b];
        String[] strArr25 = this.d;
        int i25 = this.b;
        this.b = i25 + 1;
        iVar3.a(a(new j(context26, str25, strArr25[i25], 0, 1.0f)));
        Context context27 = getContext();
        String str26 = this.d[this.b];
        String[] strArr26 = this.d;
        int i26 = this.b;
        this.b = i26 + 1;
        iVar3.a(a(new j(context27, str26, strArr26[i26], 0, 1.0f)));
        Context context28 = getContext();
        String str27 = this.d[this.b];
        String[] strArr27 = this.d;
        int i27 = this.b;
        this.b = i27 + 1;
        iVar3.a(a(new j(context28, str27, strArr27[i27], 0, 1.0f)));
        Context context29 = getContext();
        String str28 = this.d[this.b];
        String[] strArr28 = this.d;
        int i28 = this.b;
        this.b = i28 + 1;
        iVar3.a(a(new j(context29, str28, strArr28[i28], 0, 1.0f)));
        Context context30 = getContext();
        String str29 = this.d[this.b];
        String[] strArr29 = this.d;
        int i29 = this.b;
        this.b = i29 + 1;
        iVar3.a(a(new j(context30, str29, strArr29[i29], 0, 1.0f)));
        addView(iVar3);
        i iVar4 = new i(getContext());
        iVar4.a((b) new j(getContext(), "", " ", 62, 0.95f, m.a("letter_space.png"), m.a("letter_space_press.png")));
        Context context31 = getContext();
        String str30 = this.d[this.b];
        String[] strArr30 = this.d;
        int i30 = this.b;
        this.b = i30 + 1;
        iVar4.a(a(new j(context31, str30, strArr30[i30], 0, 1.0f)));
        Context context32 = getContext();
        String str31 = this.d[this.b];
        String[] strArr31 = this.d;
        int i31 = this.b;
        this.b = i31 + 1;
        iVar4.a(a(new j(context32, str31, strArr31[i31], 0, 1.0f)));
        Context context33 = getContext();
        String str32 = this.d[this.b];
        String[] strArr32 = this.d;
        int i32 = this.b;
        this.b = i32 + 1;
        iVar4.a(a(new j(context33, str32, strArr32[i32], 0, 1.0f)));
        Context context34 = getContext();
        String str33 = this.d[this.b];
        String[] strArr33 = this.d;
        int i33 = this.b;
        this.b = i33 + 1;
        iVar4.a(a(new j(context34, str33, strArr33[i33], 0, 1.0f)));
        Context context35 = getContext();
        String str34 = this.d[this.b];
        String[] strArr34 = this.d;
        int i34 = this.b;
        this.b = i34 + 1;
        iVar4.a(a(new j(context35, str34, strArr34[i34], 0, 1.0f)));
        Context context36 = getContext();
        String str35 = this.d[this.b];
        String[] strArr35 = this.d;
        int i35 = this.b;
        this.b = i35 + 1;
        iVar4.a(a(new j(context36, str35, strArr35[i35], 0, 1.0f)));
        Context context37 = getContext();
        String str36 = this.d[this.b];
        String[] strArr36 = this.d;
        int i36 = this.b;
        this.b = i36 + 1;
        iVar4.a(a(new j(context37, str36, strArr36[i36], 0, 1.0f)));
        iVar4.a((b) new com.ccb.b.b.a(getContext(), "", null, 67, 0.95f, m.a("letter_delete.png"), m.a("letter_delete_press.png")));
        addView(iVar4);
        aVar.setPrivateOnClickListener(new b(this));
    }
}
